name: Build Java EXE

on:
  push:
    paths:
      - '**.java'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17'
        distribution: 'graalvm'
        components: 'native-image'

    - name: Compile PortScanner.java
      run: javac PortScanner.java

    - name: Generate .exe using Native Image
      run: native-image -H:Name=PortScanner PortScanner

    - name: Upload PortScanner.exe
      uses: actions/upload-artifact@v3
      with:
        name: portscanner-exe
        path: PortScanner.exe
